### ISSUE TITLE
Error when running custom trained .pkl

### ISSUE THREAD

**Issue by moih** [simoncrowe/stylegan2-jack-visualizer#4]
Hi, 

Just wanted to report that when trying to visualize a custom trained model (trained with original StyleGAN2 at 1024x1024), I get this error: 
`Loading networks from /media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/Continue-prehispanicMexico.pkl...
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Loading... Failed!
Traceback (most recent call last):
  File "visualize.py", line 346, in <module>
    visualise()
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2_jack_visualizer/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2_jack_visualizer/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2_jack_visualizer/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2_jack_visualizer/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "visualize.py", line 330, in visualise
    for image_array in image_generator:
  File "visualize.py", line 127, in generate_images
    _G, _D, Gs = pretrained_networks.load_networks(network_pkl)
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2/pretrained_networks.py", line 76, in load_networks
    G, D, Gs = pickle.load(stream, encoding='latin1')
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2/dnnlib/tflib/network.py", line 297, in __setstate__
    self._init_graph()
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2/dnnlib/tflib/network.py", line 154, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 491, in G_synthesis_stylegan2
  File "<string>", line 455, in layer
  File "<string>", line 99, in modulated_conv2d_layer
  File "<string>", line 68, in apply_bias_act
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2/dnnlib/tflib/ops/fused_bias_act.py", line 68, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain)
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2/dnnlib/tflib/ops/fused_bias_act.py", line 122, in _fused_bias_act_cuda
    cuda_kernel = _get_plugin().fused_bias_act
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2/dnnlib/tflib/ops/fused_bias_act.py", line 16, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2/dnnlib/tflib/custom_ops.py", line 156, in get_plugin
    plugin = tf.load_op_library(bin_file)
  File "/media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2_jack_visualizer/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /media/hexorcismos/Archivo/AI/stylegan2-jack-visualizer/stylegan2/dnnlib/tflib/_cudacache/fused_bias_act_b9828840a052ad903f3cee6f24862064.so: undefined symbol: _ZN10tensorflow12OpDefBuilder5InputESs
`

Otherwise, the visualizer is working fine when running it using the Cats .pkl file.

Cheers!

**Comment by simoncrowe** [comment]
Do you have the same problem if you make your working directory  `stylegan2` subdirectory of this repo and run`python run_generator.py` with the same `.pkl` file. 

The bug relates to the custom CUDA code that the NVidia researchers wrote so debugging it is beyond me I think. This is the most relevant thread I found on Google: https://forums.developer.nvidia.com/t/stylegan2-error/142348 

Maybe you could try a different version of Tensorflow, switch to 1.14 if you're using 1.15 or vice versa.

**Comment by johndpope** [comment]
any chance you could throw up/paste here a screenshot? (I've been battling getting stylegan2 repos working with 3090 card for last week but very interested to see this.)

**Comment by simoncrowe** [comment]
> any chance you could throw up/paste here a screenshot? (I've been battling getting stylegan2 repos working with 3090 card for last week but very interested to see this.)

  @johndpope What would you like a screenshot of? The `visualize.py` script running?

**Comment by simoncrowe** [comment]
HI @moih, I've changed the README so people don't automatically get the wrong tf version: https://github.com/simoncrowe/stylegan2-jack-visualizer/commit/1cfdf16d0e9a9c69b0189ab3dd2121d494699233

If you're happy with that as a fix, I'll close this issue.

**Comment by simoncrowe** [comment]
Okay, I've added a screenshot and I know using an alternative Tensorflow version fixed it, so I'm closing this. If either of you have any more issues or questions, please open another issue.

**Comment by johndpope** [comment]
Thanks @simoncrowe  - looks cool. I wonder if the hack of blending of a fine tune model could yield clearer results. 
https://www.justinpinkney.com/stylegan-network-blending/

I have a branch on ada / tensorflow2
https://github.com/johndpope/stylegan2-ada/tree/digressions


UPDATE - some work by @nathanshipley 
http://www.nathanshipley.com/gan
